### ISSUE TITLE
not available in PIP

### ISSUE THREAD

**Issue by SoulRaven** [shenghaoyang/pylcddc#1]
hi,
The package is not available on PIP repository

+ not

**Comment by shenghaoyang** [comment]
> The package is available on PIP repository

I hope you mean ”not available”.

Hmm, it's there.... https://pypi.org/project/pylcddc/
Maybe I didn't push the latest release to PyPI. Gimee a bit.

**Comment by shenghaoyang** [comment]
@soulraven I've pushed the new release to pypi. Note that this package is python3 only, so if you're using `pip2`, I don't think you'll be able to find it.
